### ISSUE TITLE
Error on run

### ISSUE THREAD

**Issue by DocMAX** [NETWAYS/check_disk_btrfs#1]
File "./check_disk_btrfs", line 78
    print " ".join(cmd)
            ^
SyntaxError: invalid syntax

(but deprecated version works)

**Comment by mxhash** [comment]
How did you run the command? Python version would be also nice. I just gave it a try with python 2.7.15 ended up with no error printing the command.

**Comment by mxhash** [comment]
PING ;-) Any news?
