### ISSUE TITLE
script works only with python 2

### ISSUE THREAD

**Issue by reduzent** [NETWAYS/check_disk_btrfs#5]
Python 2 has been deprecated since the beginning of 2020. This script seems to require Python 2, nevertheless. 

Some of the more obvious failures when running with Python 3:
  * `print` is a function now
  * `raise` assumes exceptions to classes

**Comment by martialblog** [comment]
Thank you for the hint. We will have a look at it.

**Comment by martialblog** [comment]
@reduzent I just updated the script a bit. It would be great if you could test the changes on Python 3
